name: Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build an Push Dockerfile Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Dockerfile Image
        run: |
          VERSION=$(date +%s)
          docker login docker.pkg.github.com --username <username> --password ${{ secrets.GITHUB_TOKEN }}
          docker build . --file Dockerfile --tag docker.pkg.github.com/<username>/<repository>/<repository>:${VERSION}
          docker push docker.pkg.github.com/<username>/<repository>/<repository>:${VERSION}
        env:
          CI: true
